version: '3.8'

services:
  # MongoDB Service for Local Development
  mongodb:
    image: mongo:7
    container_name: mongodb_local
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: wedwisely-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wedding123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    command: mongod --auth

  # MongoDB Express (Optional - Web UI for database management)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: wedding123
      ME_CONFIG_MONGODB_URL: mongodb://admin:wedding123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: wedding123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge